guild_id: 1058822264046485527

role_management:
  staff_roles:
    - owner
    - co_owner
    - admin
    - moderator
    - dev 
    
  allowed_roles:
    - supporter
    - member_1
    - member_2
    - member_3
    - member_4

rules:
 message_id: 1058835740743700500
 reaction_role: member_1 # ← Role, die vergeben wird, wenn User auf Regeln reagiert (z.B. mit ✅)

roles:
  bot: 1058822264046485533
  owner: 1058822264046485536
  co_owner: 1096078583862140938
  admin: 1058822264046485535
  moderator: 1058822264046485534
  dev: 1482303493757993091
  supporter: 1117188071406964787
  member_1: 1058822264046485529 # Pro-Gamer
  member_2: 1058822264046485530 # Epic-Gamer
  member_3: 1058822264046485531 # Legendary-Gamer
  member_4: 1058822264046485532 #Godly-Gamer

channels:
 welcome_channel: 1058822264403017763
 member_count_vc: 1247579330784002130
 rules_channel: 1058822264860188672
 bot_status: 1487417355566055595
 dashboard_status: 1487417618318098512

log_channels:
  bot: 1058822265631940712
  moderation: 1247568105488519314

#Permlevel: MEMBER =0 / SUPPORT =5 / MOD =10 /ADMIN =20 / DEV =30 / CO_OWNER = 35 / OWNER = 40
permissions:
  warn:
    min_level: 10
  warnings:
    min_level: 5 
  del_warnings:
    min_level: 20
  timeout:
    min_level: 10
  untimeout:
    min_level: 10
  clear:
    min_level: 10
  kick:
    min_level: 20
  ban:
    min_level: 20
  unban:
    min_level: 20
  userinfo:
    min_level: 5
  devpanel:
    min_level: 30
  reload:
    min_level: 30
  role_add:
    min_level: 10
  role_remove:
    min_level: 10
  clear:
    min_level: 10
  sync_user:
    min_level: 30

security:
  lock_owner_actions: true
  admin_is_owner: false
  owner_role_only: true

moderation:
  warn_kick_threshold: 3
  warn_ban_threshold: 5
  warn_timeout_threshold: 2
  warn_timeout_duration: 300 # in seconds
  auto_action_cooldown: 60 # in seconds, Zeit, nach der Warnungen zurückgesetzt werden

automod:
  enabled: true
  spam:
    enabled: true
    message_limit: 5        # Nachrichten
    time_window: 5          # Sekunden

  caps:
    enabled: true
    threshold: 70           # Prozent Großbuchstaben
    min_length: 10          # Mindestlänge der Nachricht (kurze Nachrichten ignorieren)

  blacklist:
    enabled: true
    words:
      - "Hurensohn"
      - "Hure"
      - "Arschloch"
      - "Drecksau"
      - "Fotze"
      - "Schlampe"
      - "Wichser"
      - "Hundesohn"
      - "Missgeburt"
      - "Behinderter"
      

tickets:
  enabled: true
  #Kategorie für offene Tickets
  category_open: 1473716570986381482
  #Kategorie für closed Tickets
  category_closed: 1473716780131287322
  #Wer darf Tickets sehen
  support_min_level: 5
  #Channel-Nameing
  channel_prefix: "Ticket"
  #Archiv-Verhalten
  archive:
    hide_from_user: true
    lock_user_message: true
    #Maximale Anzahl offener Tickets pro User 
    max_open_per_user: 6

twitch:
  client_id: "8nuj95l45htu2uack2usqzuki9j9oc"
  client_secret: "6xjs549sy1u43rfqdlf75luo28ri3c"
  username: "captinchaot"
  announce_channel: 1089487400172003338
  announce_role: 1482313970537857195

birthday:
  channel_id: 1483838969442598992

features:
  admin: true                  # admin commands (Reload, Dev-Panel, etc.)
  dev: true                     # Dev-Panel + Debug-Features
  fun: true                     # Fun-Commands (Meme, etc.)
  moderation: true             # Auto-Mod (Spam/Caps/Warn-Thresholds usw.)
  roles: true                   # Role-Management (Auto-Assign, Sync, etc.)
  tickets: true                # Ticketsystem
  logging: true                # Log-Channel-Features (Moderation, Bot-Logs, etc.)
  twitch_notifications: true   # Live-Announcements
  member_count: true            # Member-Count-Channel aktualisieren
  welcome: true                 # Welcome-Message + Auto-Assign beim Beitritt 
  rules_reaction: true            # Regeln-Reactions zum Akzeptieren der Regeln
  automod: true                 # AutoMod (Spam/Caps/Blacklist)
  birthday: true                # Geburtstags-Feature (Geburtstagsdatenbank, Geburtstagsgrüße, etc.)
  status_channels: true         # Status-Channels (z.B. Bot-Status, Dashboard-Status, etc.) 
  giveaway: true                # Giveaway-Feature (Giveaways erstellen, verwalten, etc.)
  
